[package]
name = "diesel-geography"
version = "0.1.0"
authors = ["Boscop"]
edition = "2018"

[dependencies]
diesel = { version = "1.3", features = ["postgres"] }
postgis = "0.6"
serde = { version = "1.0", features = ["derive"], optional = true }
